### ISSUE TITLE
Regression about features defined with optional dependencies

### ISSUE THREAD

**Issue by asibahi** [filiptibell/tooling-language-server#17]
This is weird and did not error before.

```toml
imageproc = { version = "0.25", default-features = false, features = ["rayon"] }
# ...
either = { version = "1.13", features = ["serde"] }
```

These two lines give the errors

```json
[{
	"resource": "/Users/abdulrahmansibahi/Documents/rust/mimiron/Cargo.toml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "Unknown feature `rayon`",
	"source": "Cargo",
	"startLineNumber": 26,
	"startColumn": 71,
	"endLineNumber": 26,
	"endColumn": 78
}]
[{
	"resource": "/Users/abdulrahmansibahi/Documents/rust/mimiron/Cargo.toml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "Unknown feature `serde`",
	"source": "Cargo",
	"startLineNumber": 32,
	"startColumn": 42,
	"endLineNumber": 32,
	"endColumn": 49
}]
```

These are definitely existing feature flags. However in their respective `Cargo.toml`s they're marked as optional dependencies and not under their own `features` heading
